//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCrudApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COURSE()
        {
            this.STUDENTANDCOURSEs = new HashSet<STUDENTANDCOURSE>();
        }
    
        public int ID { get; set; }
        public string COURSENAME { get; set; }
        public Nullable<int> FEE { get; set; }
        public Nullable<System.DateTime> COURSESTART { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STUDENTANDCOURSE> STUDENTANDCOURSEs { get; set; }
    }
}
